# Generated by Django 5.1.2 on 2024-12-11 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shinku_1', '0002_userinfo_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_group',
        ),
    ]
