# Generated by Django 5.1.2 on 2024-12-11 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinku_1', '0004_userinfo_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='owner',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shinku_1.userinfo'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=14, verbose_name='订单号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='购买时间')),
                ('status', models.SmallIntegerField(choices=[(0, '订单失败'), (1, '订单支付中'), (2, '订单完成')], default=1, verbose_name='状态')),
                ('buyer', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='buyer', to='shinku_1.userinfo', verbose_name='买家')),
                ('seller', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='seller', to='shinku_1.userinfo', verbose_name='卖家')),
            ],
        ),
    ]
