# Generated by Django 5.1.2 on 2024-12-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinku_1', '0005_goods_owner_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.PositiveIntegerField(verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='114514', max_length=14, verbose_name='订单号'),
        ),
    ]
