# Generated by Django 5.1.2 on 2024-12-12 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinku_1', '0006_alter_goods_price_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='邮箱'),
        ),
    ]
