# Generated by Django 5.1.2 on 2024-12-12 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinku_1', '0007_alter_userinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格'),
        ),
    ]
