# Generated by Django 5.1.2 on 2024-12-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shinku_1', '0008_alter_goods_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='buyer', to='shinku_1.userinfo', verbose_name='买家'),
        ),
        migrations.AlterField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='seller', to='shinku_1.userinfo', verbose_name='卖家'),
        ),
    ]
